version: '3.5'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trophy-next
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000