version: '3.5'

services:
  trophy_nextjs:
    build:
      context: ../
      dockerfile: ./.docker/node/Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    restart: always
    container_name: trophy_nextjs
    volumes:
      # change to your app path
      - /home/apps/sites/moderntrophy/logs:/home/node/app/logs:rw
      - /home/apps/sites/moderntrophy/package-lock.json:/home/node/app/package-lock.json:rw
    networks:
      - sa_trophy

  trophy_nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    restart: always
    container_name: trophy_nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.trophy_nginx.rule=Host(`moderntrophy.com`)"
      # - "traefik.http.routers.trophy_nginx.entrypoints=websecure"
      # - "traefik.http.routers.trophy_nginx.tls=true"
    networks:
      - sa_trophy

networks:
  sa_trophy:
    external: true